### ISSUE TITLE
pump throttle

### ISSUE THREAD

**Issue by dcerisano** [mafintosh/pump#1]
Could you verify that this where a throttle would be placed?

**Comment by mafintosh** [comment]
I'm not sure what you mean? Is this related to the pump module or one of my bittorrent ones?

**Comment by dcerisano** [comment]
Sorry, I must be way off asking this. I thought that your bittorrent libraries depended on this pump module.

**Comment by mafintosh** [comment]
You can use pump both in the client or in a server. It uses pipe underneath the hood so it does backpressure for you.
