### ISSUE TITLE
Consider switching to promise based API

### ISSUE THREAD

**Issue by LinusU** [mafintosh/pump#11]
Since promises is being embraced more and more in the Node.js community, I would just like to see if there is any interest in releasing a new major version of this module which returns a `Promise` instead of taking a callback. I personally would find this very convenient since I'm currently "promisifying" this library before I use it. This would also solve #9 in the same go...

I'd be happy to submit a pull request, thanks for the consideration 👌

**Comment by mafintosh** [comment]
Thanks for the offer but I prefer the callback API for a variety of reasons.

**Comment by hlehmann** [comment]
A very common pattern: if a callback is provided it use it, if not it return a promise.

Having the ability to have promise will be very usefull, currently I'm using:
```
await new Promise((resolve, reject) => {
  pump(...streams, (err) => {
    if (err) return reject(err);
    resolve();
  });
});
```

**Comment by Kikobeats** [comment]
Promise support can be done out of the box using Node.js built-in:

```js
const { promisify } = require('util')
const pump = promisify(require('pump'))

// later
await pump(got.stream(url, opts), fs.createWriteStream(tmpPath))
```
