### ISSUE TITLE
Arrays-in-arrays to create reuseable functions

### ISSUE THREAD

**Issue by elygre** [mafintosh/pump#15]
Using gulp, we often find ourselves creating pipelines that end with the same few transforms.

```
    pump([
        src("somefiles/**/*.js"),
        somtransformation(),
        rename(renameMin),
        uglify(),
        dest("/somedirectory")
    ], cb);
```

It would be nice if the input arguments could be flattened first, to allow for subarrays:

```
    pump([
        src("somefiles/**/*.js"),
        somtransformation(),
        [
            rename(renameMin),
            uglify(),
            dest("/somedirectory")
        ]
    ], cb);
```

This would enable us to write this code, where the function `tail()` returns a partial pipeline:

```
const tail = function(dir) {
    return [ 
        rename(renameMin),
        uglify(),
        dest(dir)
    ];
}

    pump([
        src("somefiles/**/*.js"),
        somtransformation(),
        tail("/somedirectory")
    ], cb);
```

**Comment by yoshuawuyts** [comment]
I think that should be a different module tbh, pump is core infrastructure
at this point - changing the API for more features that can easily be
resolved in userland doesn't seem like a great idea.

**Comment by mafintosh** [comment]
Use [pumpify](https://github.com/mafintosh/pumpify) to make sub pipelines

``` js
const tail = function(dir) {
    return pumpify([ 
        rename(renameMin),
        uglify(),
        dest(dir)
    ]);
}
```
