### ISSUE TITLE
bring into node core

### ISSUE THREAD

**Issue by calvinmetcalf** [mafintosh/pump#17]
At the face to face in Berlin we brought up bringing this into core and exposing it as `require('stream').pump`.  A couple questions:

1. are you ok with this idea?
2. do you want to open the pull or are you ok if I or @mcollina does so?
3. How do you feel about waving copyright on this and end-of-stream? It's OK if you don't want to do so but if you do it will make it significantly less complicated to bring it into node core.

**Comment by mafintosh** [comment]
1. Sure, as long as these modules stay backwards compat <4 without any babel stuff
1. You should probably do it
1. I'm okay waving copyright.

**Comment by calvinmetcalf** [comment]
great thanks!

**Comment by mafintosh** [comment]
@calvinmetcalf also cool initiative, forgot to say that.

**Comment by phated** [comment]
This is complete but #41 is needed to inline both APIs.

**Comment by mcollina** [comment]
BTW, this is now in core. We have `require('stream').pipeline`.

**Comment by mcollina** [comment]
(this can be closed).
