### ISSUE TITLE
Callback not called with stdout/stderr

### ISSUE THREAD

**Issue by julien-f** [mafintosh/pump#19]
Probably because they don't emit the `finish`, but it would be nice to handle them properly anyway.

It's unfortunate because in my CLI I often do:
```js
pump(
  inputStream,
  output  === undefined || output === '-'
    ? process.stdout
    : createWriteStream(output),
  () => {
    // do some cleanup after transfer
  }
)
```

**Comment by mafintosh** [comment]
Try using my stdout-stream module instead of process.stdout

**Comment by julien-f** [comment]
I use a passthrough stream piped to stdout to work around the issue.

Thanks for your answer :)
