### ISSUE TITLE
pump on "unclosable" stream

### ISSUE THREAD

**Issue by allevo** [mafintosh/pump#20]
According to nodejs documentation, not all streams emit `close` event, `process.stdout` is an example.

In the classic situation like this:
```
pump(readableStream, transformStream, process.stdout, function (err) {
  console.log('END', err)
})
```
the log is never printed

To make a workaround I wrote:
```
pump(stream, transform, function (err) {
  console.log('END', err)
}).pipe(outputStream)
```

Is there another way more elegant to write this?

**Comment by mafintosh** [comment]
yea stdout doesn't end so pump won't call the callback. what you can do it use [stdout-stream](https://github.com/mafintosh/stdout-stream) instead and it should work as expected

**Comment by allevo** [comment]
Many thanks for your suggestions.
