### ISSUE TITLE
returning last stream

### ISSUE THREAD

**Issue by pgte** [mafintosh/pump#27]
Before version 2, `pump()` used to return the last stream, and apparently now it doesn't.
Even though this wasn't a documented feature before, I find it really useful to simplify the code.

pump@1:

```js
return pump(s1, s2)
```

pump@2:

```js
pump(s1, s2)
return s2
```

Do you think this could be a useful feature? If so, I'm willing to add a PR.

**Comment by yoshuawuyts** [comment]
This was explicitely removed as per https://github.com/mafintosh/pump/pull/18.

**Comment by mafintosh** [comment]
I miss this feature as well actually. Could you open a PR that readds it +
docs? Then we can decide finally in there if it should be reverted back :)

**Comment by phated** [comment]
I don't understand what you miss about the feature.  It didn't actually work correctly and the use cases are solved by pumpify.  @mafintosh can you explain further?

**Comment by mafintosh** [comment]
The main usecase is returning the result of a pipeline, similar to doing
`return a.pipe(b)` you'd do `return pump(a, b)`. This makes sense when you
want to return the last readable stream. Like I mentioned a PR that adds
docs is a better place to discuss it so all are on the same page about what
it does and whether it should be reverted. Pros and cons :)

**Comment by mafintosh** [comment]
Out in 3.0.0
