### ISSUE TITLE
Multiple pumps inside a single task

### ISSUE THREAD

**Issue by janrembold** [mafintosh/pump#28]
Is there any best-practice-way of using multiple pumps inside a single task and return the callback after all of them finished?

Maybe a simplified demo code clearifies the question:

```javascript
gulp.task('compress', function (cb) {
  const folders = ['folder1', 'folder2'];

  folders.forEach((folder) => {
    pump([
        gulp.src(`lib/${folder}/*.js`),
        uglify(),
        gulp.dest(`${folder}/dist/`)
      ],
      cb // <= this is wrong of course
    );
  });  

  // cb(); // calling it here might be as wrong as well
});
```

This is, of course, not a real life code snippet. But it shows the need to run multiple pumps inside a single task. In my real case the source and destination folders are a little bit more complex. 

Is there any way to solve that with pump?

**Comment by janrembold** [comment]
We solved this by adding Promises around each pump and call the callback function after all promises got resolved. See https://github.com/biotope/biotope-build/blob/master/tasks/uglify.js#L25

**Comment by zhuchuji** [comment]
Hi, how to make the code work in the above example? I face the same problem and it throws the error: task completion callback called too many times.

**Comment by janrembold** [comment]
@zhuchuji Please see the link above for a working example using Promises. You should only call cb() once

**Comment by zhuchuji** [comment]
@janrembold Got it. Thank you.
