### ISSUE TITLE
pump + webpack-stream exits watch task

### ISSUE THREAD

**Issue by janrembold** [mafintosh/pump#39]
The combination of webpack-stream and pump exits the watch task on error during webpack execution. I used the same pattern as the uglify example here: https://github.com/gulpjs/gulp/tree/master/docs/why-use-pump

Is this most likely an issue within webpack-stream (maybe it doesn't exit correctly?) or is there any option in pump to not exit on error??? I thought pump does exactly this -> to reliably catch errors and does not exit the running watch process...

**Comment by mafintosh** [comment]
pump doesn't exit on error. it shuts down the streams in the pipeline, by calling .destroy on all of them. this sounds like an error in the module you are using.

**Comment by janrembold** [comment]
Wouldn't be the first issue in the webpack-stream module :( Thank you for the quick reply!!! Think we are going to remove it completely soon
