### ISSUE TITLE
pump swallowing errors when read stream is empty

### ISSUE THREAD

**Issue by coderaiser** [mafintosh/pump#45]
`pump` has inconsistent behavior with `pipe`, it is swallows writable errors, when readable stream is empty, for example, such code will log `undefined`:

```js
const {Readable} = require('stream');
const {createWriteStream} = require('fs');
const pump = require('pump');

const inStream = new Readable({
  read() {}
});

inStream.push(null);

pump(inStream, createWriteStream('/'), console.log);
```

And this one will show an error:

```js
const {Readable} = require('stream');
const {createWriteStream} = require('fs');
const pump = require('pump');

const inStream = new Readable({
  read() {}
});

inStream.push(null);
inStream.pipe(createWriteStream('/'));
```

This relates to https://github.com/nodejs/node/issues/24517

**Comment by mcollina** [comment]
It is the exact same issue, and see my long explanation there. I'm almost certain @mafintosh thinks the same way.

**Comment by mafintosh** [comment]
What @mcollina said
