### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [mafintosh/pump#46]
Hi, what is the current status of this project? Is it still actively maintained?

**Comment by mafintosh** [comment]
Yep!

**Comment by matthiasg** [comment]
Good to hear. Am I correct though that beginning with Node 10 and stream.pipeline pump is not longer required ? If so i think it would be appreciated if the README commented on to why or why not ?

**Comment by lukesims** [comment]
@matthiasg you are correct - the following quote from the [Node docs](https://nodejs.org/en/docs/guides/backpressuring-in-streams) confirms it:

> [`pump`](https://github.com/mafintosh/pump) is only necessary for Nodejs 8.x or earlier, as for Node 10.x or later version, [`pipeline`](https://nodejs.org/api/stream.html#stream_stream_pipeline_streams_callback) is introduced to replace for [`pump`](https://github.com/mafintosh/pump). This is a module method to pipe between streams forwarding errors and properly cleaning up and provide a callback when the pipeline is complete.

**Comment by mafintosh** [comment]
Yup, in Node.js 10 pipeline was added (by me :)) to have pump in core. I still use pump personally whenever I want to support Node.js <10

**Comment by matthiasg** [comment]
@mafintosh @lukesims sorry had actually read it in the node docs, but had forgotten about it. It would be sensible to mention in this projects README as well though, to close the loop for people coming from other projects (like I did) trying to figure out whether its required. good work btw

**Comment by lukesims** [comment]
I agree with @matthiasg as it would save future users from making the same side-trip to the Node docs that we all did to reach this conclusion. [This is the PR](https://github.com/nodejs/node/pull/19828) if anyone else is interested - good work @mafintosh :)
