### ISSUE TITLE
callback in pump firing before _flush complete

### ISSUE THREAD

**Issue by andrewnaeve** [mafintosh/pump#47]
This is probably a request for clarification rather than a bug report. I have a transform stream with an `async _flush` method. However, pump's callback fires before I call the callback in flush. As a result, my app terminates early. If instead of using pump, I just resolve a promise on the 'end' event, my app functions normally. Is there something about using `async await` inside _flush in a transform stream that breaks pump, or is bad practice?

**Comment by mafintosh** [comment]
Pump calls the callback when the final stream in the pipeline emits `finish` which is an event indicating that the *writable* side of that stream is fully flushed.

The flush method is called just before the *readable* side of the stream ends.

Use _final instead if you want to do something before the writable side is done.

**Comment by andrewnaeve** [comment]
Thanks for clarifying!
