### ISSUE TITLE
The latest update throws an exception in older versions of nodejs

### ISSUE THREAD

**Issue by rossroma** [mafintosh/pump#59]
![image](https://github.com/user-attachments/assets/c78dcedd-8f73-4146-8d23-09abb0f8aad2)

nodejs version: 12.16.2

**Comment by trile-amb** [comment]
the same issue with node 8x & 10x

**Comment by aparajit007** [comment]
https://github.com/mafintosh/pump/pull/60
@mafintosh Please merge this, it will fix this issue.

**Comment by july-maker** [comment]
Introduce the pump3.0.0 version package in the project package.json file to temporarily resolve the issue
