### ISSUE TITLE
Pump synchronized ?

### ISSUE THREAD

**Issue by Elfayer** [mafintosh/pump#7]
I have an issue, I'm using pump on every tasks I have (there is 4):
- compileTS
- minify
- concat
- unitTests

I need all these tasks to be synchronous, so I use [gulp-sync](https://www.npmjs.com/package/gulp-sync). But it still seems that tasks are asynchronous. I'm wondering if it comes from Pump ?

**Note:** I can provide more details if needed.

**Comment by feross** [comment]
Your issue is that streams in Node.js are async and there's no way to make them sync. Since `pump` just operates on streams, there's nothing that `pump` can do to fix this.

**Comment by mafintosh** [comment]
what @feross said
