### ISSUE TITLE
stream remains active after pump callback when error does not terminate stream

### ISSUE THREAD

**Issue by pabigot** [mafintosh/pump#8]
If a readable stream in a pump chain emits an error but continues to produce data the pump callback will be invoked at the point of error and the stream will continue to run.  The callback will not be re-invoked when/if the streams actually close.  This appears to be due to internal use of [end-of-stream](https://www.npmjs.com/package/end-of-stream) which assumes "failure" and closure are coincident.

Sample code [here](https://gist.github.com/pabigot/aa7a7f7db0c702dca556c7eac948d330).

A stream that continues after an error is certainly unusual, but it's legal, and pump does not fulfill its responsibility by invoking the callback and shutting down the remaining pipe stages when the stream actually closes or errors at dest in this situation.  I'm not going to argue strongly that it should, but IMO saying it shouldn't isn't trivially justifiable either.  So, your call.

**Comment by mafintosh** [comment]
it will call destroy on all streams in this case. try adding that method to your streams in your example.
